ci:
  autofix_commit_msg: "ci(pre-commit): autofix"
  autoupdate_commit_msg: "ci(pre-commit): autoupdate"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.36.0
    hooks:
      - id: markdownlint
        args: [-c, .markdownlint.yaml, --fix]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.32.0
    hooks:
      - id: yamllint

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.5
    hooks:
      - id: shellcheck

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.7.0-1
    hooks:
      - id: shfmt
        args: [-w, -s, -i=4]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        args: [--line-length=100]

  - repo: https://github.com/tier4/pre-commit-hooks-ros
    rev: v0.8.0
    hooks:
      - id: flake8-ros

  - repo: https://github.com/ComPWA/mirrors-pyright
    rev: v1.1.325
    hooks:
      - id: pyright

  - repo: local
    hooks:
      - id: format-words
        name: format words.txt
        description: Format words.txt.
        entry: python tier4_cspell_dicts/format_words.py
        language: python
        files: .*words.txt$
