name: pytest

on:
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependent packages
        run: |
          pip install poetry
          poetry install

      - name: Run pytest
        run: |
          poetry run pytest -s
